name: flutter_artefak
description: "A new Flutter project."
publish_to: 'none'  # Tidak dipublikasikan ke pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1  # Pastikan menggunakan versi Dart SDK yang kompatibel

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  file_picker: ^10.0.0
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  http: ^1.4.0
  provider: ^6.0.5
  url_launcher: ^6.1.10
  shimmer: ^3.0.0
  dio: ^5.3.2
  path_provider: ^2.1.1
  permission_handler: ^11.0.0
  open_file: ^3.3.2
  share_plus: ^7.1.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

# Pengaturan untuk mengganti ikon aplikasi menggunakan flutter_launcher_icons
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"  # Pastikan path gambar ikon sudah benar
  android_icon_size: 192  # Ukuran ikon untuk Android
  ios_icon_size: 180  # Ukuran ikon untuk iOS
  remove_alpha_ios: true  # Menghapus alpha channel untuk iOS

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png # Pastikan gambar ini ada di dalam folder assets/